import { Model, Session } from "./core/IModel";
import { v4 as uuidv4 } from 'uuid';
import openaiLogo from "@/assets/logos/openai.png";
import anthropicLogo from "@/assets/logos/anthropic.png";
import deepseekLogo from "@/assets/logos/deepseek.png";
import geminiLogo from "@/assets/logos/google.png";
import groqLogo from "@/assets/logos/groq.png";
import xaiLogo from "@/assets/logos/xai.png";
import mistralLogo from "@/assets/logos/mistral.png";
import cohereLogo from "@/assets/logos/cohere.png";
import novaLogo from "@/assets/logos/nova.png";


export const providerLogo = {
  "OpenAI": openaiLogo,
  "Anthropic": anthropicLogo,
  "Deepseek": deepseekLogo,
  "Google": geminiLogo,
  "Groq": groqLogo,
  "xAI": xaiLogo,
  "Mistral": mistralLogo,
  "Cohere": cohereLogo,
  "Nova": novaLogo,
}

export const models: Model[] = [
  {
    id: "1",
    provider: "OpenAI",
    name: "openai:gpt-4o-mini",
    displayName: "OpenAI GPT-4o-mini",
    description: "Fast, affordable small model for focused tasks",
    contextWindow: 128000,
    maxOutputTokens: 16384,
    parameters: {
      temperature: 0.7,
      maxTokens: 2048,
      topP: 1,
    },
    pricing: {
      inputPrice: 0.15,
      outputPrice: 0.6,
    },
    inputTypes: {
      text: true,
      image: true,
      audio: false,
      video: false,
    },
    knowledgeCutoff: "10/01/2023",
    modelPageUrl: "https://platform.openai.com/docs/models/gpt-4o-mini",
    pricingUrl: "https://openai.com/api/pricing/",
    websiteUrl: "https://openai.com/",
  },
  {
    id: "2",
    provider: "OpenAI",
    name: "openai:gpt-4o",
    displayName: "OpenAI GPT-4o",
    description: "Fast, intelligent, flexible GPT model",
    contextWindow: 128000,
    maxOutputTokens: 16384,
    parameters: {
      temperature: 0.7,
      maxTokens: 2048,
      topP: 1,
    },
    pricing: {
      inputPrice: 2.5,
      outputPrice: 10,
    },
    inputTypes: {
      text: true,
      image: true,
      audio: false,
      video: false,
    },
    knowledgeCutoff: "10/01/2023",
    modelPageUrl: "https://platform.openai.com/docs/models/gpt-4o",
    pricingUrl: "https://openai.com/api/pricing/",
    websiteUrl: "https://openai.com/",
  },
  {
    id: "3",
    provider: "OpenAI",
    name: "openai:gpt-3.5-turbo",
    displayName: "OpenAI GPT-3.5-turbo",
    description: "The latest and most powerful GPT model",
    contextWindow: 16385,
    maxOutputTokens: 4096,
    parameters: {
      temperature: 0.7,
      maxTokens: 2048,
      topP: 1,
    },
    pricing: {
      inputPrice: 0.5,
      outputPrice: 0.0002,
    },
    inputTypes: {
      text: true,
      image: false,
      audio: false,
      video: false,
    },
    knowledgeCutoff: "09/01/2021",
    modelPageUrl: "https://platform.openai.com/docs/models/gpt-3.5-turbo",
    pricingUrl: "https://openai.com/api/pricing/",
    websiteUrl: "https://openai.com/",
  },
  {
    id: "4",
    provider: "OpenAI",
    name: "openai:gpt-4o-audio-preview",
    displayName: "OpenAI GPT-4o Audio Preview",
    description: "Fast, affordable small model for focused tasks",
    contextWindow: 128000,
    maxOutputTokens: 16384,
    parameters: {
      temperature: 0.7,
      maxTokens: 2048,
      topP: 1,
    },
    pricing: {
      inputPrice: 2.5,
      outputPrice: 10,
      audioInputPrice: 40,
      audioOutputPrice: 80,
    },
    inputTypes: {
      text: true,
      image: false,
      audio: true,
      video: false,
    },
    knowledgeCutoff: "10/01/2023",
    modelPageUrl: "https://platform.openai.com/docs/models/gpt-4o-audio-preview",
    pricingUrl: "https://openai.com/api/pricing/",
    websiteUrl: "https://openai.com/",
  },
  {
    id: "5",
    provider: "OpenAI",
    name: "openai:gpt-4-turbo",
    displayName: "OpenAI GPT-4 Turbo",
    description: "The latest and most powerful GPT model",
    contextWindow: 128000,
    maxOutputTokens: 4096,
    parameters: {
      temperature: 0.7,
      maxTokens: 2048,
      topP: 1,
    },
    pricing: {
      inputPrice: 10,
      outputPrice: 30,
    },
    inputTypes: {
      text: true,
      image: true,
      audio: false,
      video: false,
    },
    knowledgeCutoff: "12/01/2023",
    modelPageUrl: "https://platform.openai.com/docs/models/gpt-4-turbo",
    pricingUrl: "https://openai.com/api/pricing/",
    websiteUrl: "https://openai.com/",
  },
  {
    id: "6",
    provider: "OpenAI",
    name: "openai:gpt-4",
    displayName: "OpenAI GPT-4",
    description: "The latest and most powerful GPT model",
    contextWindow: 8192,
    maxOutputTokens: 8192,
    parameters: {
      temperature: 0.7,
      maxTokens: 2048,
      topP: 1,
    },
    pricing: {
      inputPrice: 30,
      outputPrice: 60,
    },
    inputTypes: {
      text: true,
      image: true,
      audio: false,
      video: false,
    },
    knowledgeCutoff: "12/01/2023",
    modelPageUrl: "https://platform.openai.com/docs/models/gpt-4",
    pricingUrl: "https://openai.com/api/pricing/",
    websiteUrl: "https://openai.com/",
  },
  {
    id: "7",
    provider: "OpenAI",
    name: "openai:o1",
    displayName: "OpenAI o1",
    description: "Previous full o-series reasoning model",
    contextWindow: 200000,
    maxOutputTokens: 100000,
    parameters: {
      temperature: 0.7,
      maxTokens: 2048,
      topP: 1,
      reasoningEffort: 'low',
    },
    pricing: {
      inputPrice: 15,
      outputPrice: 60,
    },
    inputTypes: {
      text: true,
      image: true,
      audio: false,
      video: false,
    },
    knowledgeCutoff: "10/01/2023",
    modelPageUrl: "https://platform.openai.com/docs/models/o1",
    pricingUrl: "https://openai.com/api/pricing/",
    websiteUrl: "https://openai.com/",
  },
  {
    id: "8",
    provider: "OpenAI",
    name: "openai:o1-mini",
    displayName: "OpenAI o1 Mini",
    description: "Previous full o-series reasoning model",
    contextWindow: 128000,
    maxOutputTokens: 65536,
    parameters: {
      temperature: 0.7,
      maxTokens: 2048,
      topP: 1,
      reasoningEffort: 'low',
    },
    pricing: {
      inputPrice: 1.1,
      outputPrice: 4.4,
    },
    inputTypes: {
      text: true,
      image: true,
      audio: false,
      video: false,
    },
    knowledgeCutoff: "10/01/2023",
    modelPageUrl: "https://platform.openai.com/docs/models/o1-mini",
    pricingUrl: "https://openai.com/api/pricing/",
    websiteUrl: "https://openai.com/",
  },
  {
    id: "9",
    provider: "OpenAI",
    name: "openai:o3",
    displayName: "OpenAI o3",
    description: "Our most powerful reasoning model",
    contextWindow: 200000,
    maxOutputTokens: 100000,
    parameters: {
      temperature: 0.7,
      maxTokens: 2048,
      topP: 1,
      reasoningEffort: 'low',
    },
    pricing: {
      inputPrice: 10,
      outputPrice: 40,
    },
    inputTypes: {
      text: true,
      image: true,
      audio: false,
      video: false,
    },
    knowledgeCutoff: "6/01/2024",
    modelPageUrl: "https://platform.openai.com/docs/models/o3",
    pricingUrl: "https://openai.com/api/pricing/",
    websiteUrl: "https://openai.com/",
  },
  {
    id: "10",
    provider: "OpenAI",
    name: "openai:o3-mini",
    displayName: "OpenAI o3 Mini",
    description: "A small model alternative to o3",
    contextWindow: 200000,
    maxOutputTokens: 100000,
    parameters: {
      temperature: 0.7,
      maxTokens: 2048,
      topP: 1,
      reasoningEffort: 'low',
    },
    pricing: {
      inputPrice: 1.1,
      outputPrice: 4.4,
    },
    inputTypes: {
      text: true,
      image: false,
      audio: false,
      video: false,
    },
    knowledgeCutoff: "10/01/2023",
    modelPageUrl: "https://platform.openai.com/docs/models/o3-mini",
    pricingUrl: "https://openai.com/api/pricing/",
    websiteUrl: "https://openai.com/",    
  },
  {
    id: "11",
    provider: "Anthropic",
    name: "anthropic:claude-3-5-haiku-20241022",
    displayName: "Anthropic Claude 3.5 Haiku",
    description: "Anthropic's fastest model",
    contextWindow: 200000,
    maxOutputTokens: 8192,
    parameters: {
      temperature: 0.7,
      maxTokens: 2048,
      topP: 1,
    },
    pricing: {
      inputPrice: 0.8,
      outputPrice: 4,
    },
    inputTypes: {
      text: true,
      image: false,
      audio: false,
      video: false,
    },
    knowledgeCutoff: "10/01/2023",
    modelPageUrl: "https://www.anthropic.com/claude/haiku",
    pricingUrl: "https://www.anthropic.com/pricing",
    websiteUrl: "https://www.anthropic.com/",    
  },
  {
    id: "12",
    provider: "Anthropic",
    name: "anthropic:claude-3-5-sonnet-20241022",
    displayName: "Anthropic Claude 3.5 Sonnet",
    description: "Anthropic's previous intellignet model",
    contextWindow: 200000,
    maxOutputTokens: 8192,
    parameters: {
      temperature: 0.7,
      maxTokens: 8192,
      topP: 1,
    },
    pricing: {
      inputPrice: 3,
      outputPrice: 15,
    },
    inputTypes: {
      text: true,
      image: true,
      audio: false,
      video: false,
    },
    knowledgeCutoff: "04/01/2024",
    modelPageUrl: "https://docs.anthropic.com/en/docs/about-claude/models/overview",
    pricingUrl: "https://www.anthropic.com/pricing",
    websiteUrl: "https://www.anthropic.com/",    
  },
  {
    id: "13",
    provider: "Anthropic",
    name: "anthropic:claude-3-7-sonnet-20250219",
    displayName: "Anthropic Claude 3.7 Sonnet",
    description: "Anthropic's high performance model with extended thinking",
    contextWindow: 200000,
    maxOutputTokens: 64000,
    parameters: {
      temperature: 0.7,
      maxTokens: 2048,
      topP: 1,
      thinking: {
        type: "enabled",
        budget_tokens: 10000,
      }
    },
    pricing: {
      inputPrice: 3,
      outputPrice: 15,
    },
    inputTypes: {
      text: true,
      image: true,
      audio: false,
      video: false,
    },
    knowledgeCutoff: "11/01/2024",
    modelPageUrl: "https://www.anthropic.com/claude/haiku",
    pricingUrl: "https://www.anthropic.com/pricing",
    websiteUrl: "https://www.anthropic.com/",    
  },
  {
    id: "14",
    provider: "Anthropic",
    name: "anthropic:claude-3-haiku-20240307",
    displayName: "Anthropic Claude 3 Haiku",
    description: "Anthropic's fast and compact model for near-instant responsiveness",
    contextWindow: 200000,
    maxOutputTokens: 4096,
    parameters: {
      temperature: 0.7,
      maxTokens: 2048,
      topP: 1,
    },
    pricing: {
      inputPrice: 0.25,
      outputPrice: 1.25,
    },
    inputTypes: {
      text: true,
      image: true,
      audio: false,
      video: false,
    },
    knowledgeCutoff: "11/01/2023",
    modelPageUrl: "https://docs.anthropic.com/en/docs/about-claude/models/overview",
    pricingUrl: "https://www.anthropic.com/pricing",
    websiteUrl: "https://www.anthropic.com/",    
  },
  {
    id: "15",
    provider: "Anthropic",
    name: "anthropic:claude-3-opus-20240229",
    displayName: "Anthropic Claude 3 Opus",
    description: "Anthropic's powerful model for complex tasks",
    contextWindow: 200000,
    maxOutputTokens: 4096,
    parameters: {
      temperature: 0.7,
      maxTokens: 4096,
      topP: 1,
    },
    pricing: {
      inputPrice: 15,
      outputPrice: 75,
    },
    inputTypes: {
      text: true,
      image: true,
      audio: false,
      video: false,
    },
    knowledgeCutoff: "11/01/2023",
    modelPageUrl: "https://docs.anthropic.com/en/docs/about-claude/models/overview",
    pricingUrl: "https://www.anthropic.com/pricing",
    websiteUrl: "https://www.anthropic.com/",    
  },
  {
    id: "16",
    provider: "Anthropic",
    name: "anthropic:claude-opus-4-20250514",
    displayName: "Anthropic Claude 4 Opus",
    description: "Anthropic's most powerful reasoning model",
    contextWindow: 200000,
    maxOutputTokens: 32000,
    parameters: {
      temperature: 0.7,
      maxTokens: 2048,
      topP: 1,
      thinking: {
        type: "enabled",
        budget_tokens: 10000,
      }
    },
    pricing: {
      inputPrice: 15,
      outputPrice: 75,
    },
    inputTypes: {
      text: true,
      image: false,
      audio: false,
      video: false,
    },
    knowledgeCutoff: "03/01/2025",
    modelPageUrl: "https://www.anthropic.com/claude/haiku",
    pricingUrl: "https://www.anthropic.com/pricing",
    websiteUrl: "https://www.anthropic.com/",    
  },
  {
    id: "17",
    provider: "Anthropic",
    name: "anthropic:claude-sonnet-4-20250514",
    displayName: "Anthropic Claude 4 Sonnet",
    description: "Anthropic's high performance model",
    contextWindow: 200000,
    maxOutputTokens: 64000,
    parameters: {
      temperature: 0.7,
      maxTokens: 2048,
      topP: 1,
      thinking: {
        type: "enabled",
        budget_tokens: 10000,
      }
    },
    pricing: {
      inputPrice: 3,
      outputPrice: 15,
    },
    inputTypes: {
      text: true,
      image: true,
      audio: false,
      video: false,
    },
    knowledgeCutoff: "03/01/2025",
    modelPageUrl: "https://www.anthropic.com/claude/sonnet",
    pricingUrl: "https://www.anthropic.com/pricing",
    websiteUrl: "https://www.anthropic.com/",    
  },
  {
    id: "18",
    provider: "Deepseek",
    name: "deepseek:deepseek-chat",
    displayName: "Deepseek Chat",
    description: "Deepseek's powerful model for complex tasks",
    contextWindow: 64000,
    maxOutputTokens: 8000,
    parameters: {
      temperature: 0.7,
      maxTokens: 8000,
      topP: 1,
    },
    pricing: {
      inputPrice: 0.27,
      outputPrice: 1.1,
    },
    inputTypes: {
      text: true,
      image: false,
      audio: false,
      video: false,
    },
    knowledgeCutoff: "03/01/2025",
    modelPageUrl: "https://www.deepseek.com/models/deepseek-chat",
    pricingUrl: "https://www.deepseek.com/pricing",
    websiteUrl: "https://www.deepseek.com/",    
  },
  {
    id: "19",
    provider: "Deepseek",
    name: "deepseek:deepseek-reasoner",
    displayName: "Deepseek Reasoner",
    description: "Deepseek's powerful model for complex tasks",
    contextWindow: 64000,
    maxOutputTokens: 8000,
    parameters: {
      temperature: 0.7,
      maxTokens: 8000,
      topP: 1,
    },
    pricing: {
      inputPrice: 0.55,
      outputPrice: 2.19,
    },
    inputTypes: {
      text: true,
      image: false,
      audio: false,
      video: false,
    },
    knowledgeCutoff: "03/01/2025",
    modelPageUrl: "https://www.deepseek.com/models/deepseek-reasoner",
    pricingUrl: "https://www.deepseek.com/pricing",
    websiteUrl: "https://www.deepseek.com/",    
  },
  {
    id: "20",
    provider: "Google",
    name: "google:gemini-1.5-flash",
    displayName: "Gemini 1.5 Flash 002",
    description: "Gemini 1.5 Flash is a fast and versatile multimodal model for scaling across diverse tasks.",
    contextWindow: 1048576,
    maxOutputTokens: 8192,
    parameters: {
      temperature: 0.7,
      maxTokens: 8192,
      topP: 1,
    },
    pricing: {
      inputPrice: 0.15,
      outputPrice: 0.60,
    },
    inputTypes: {
      text: true,
      image: true,
      audio: true,
      video: true,
    },
    knowledgeCutoff: "09/01/2024",
    modelPageUrl: "https://deepmind.google/models/gemini/flash/",
    pricingUrl: "https://www.google.com/pricing",
    websiteUrl: "https://www.google.com/",    
  },
  {
    id: "21",
    provider: "Google",
    name: "google:gemini-1.5-flash-8b",
    displayName: "Gemini 1.5 Flash 8b",
    description: "Gemini 1.5 Flash-8B is a small model designed for lower intelligence tasks.",
    contextWindow: 1048576,
    maxOutputTokens: 8192,
    parameters: {
      temperature: 0.7,
      maxTokens: 8192,
      topP: 1,
    },
    pricing: {
      inputPrice: 0.075,
      outputPrice: 0.30,
    },
    inputTypes: {
      text: true,
      image: true,
      audio: true,
      video: true,
    },
    knowledgeCutoff: "10/01/2024",
    modelPageUrl: "https://deepmind.google/models/gemini/flash/",
    pricingUrl: "https://www.google.com/pricing",
    websiteUrl: "https://www.google.com/",    
  },
  {
    id: "22",
    provider: "Google",
    name: "google:gemini-1.5-pro",
    displayName: "Gemini 1.5 Pro 002",
    description: "Gemini 1.5 Pro is a mid-size multimodal model that is optimized for a wide-range of reasoning tasks. 1.5 Pro can process large amounts of data at once, including 2 hours of video, 19 hours of audio, codebases with 60,000 lines of code, or 2,000 pages of text.",
    contextWindow: 2097152,
    maxOutputTokens: 8192,
    parameters: {
      temperature: 0.7,
      maxTokens: 8192,
      topP: 1,
    },
    pricing: {
      inputPrice: 0.35,
      outputPrice: 1.35,
    },
    inputTypes: {
      text: true,
      image: true,
      audio: true,
      video: true,
    },
    knowledgeCutoff: "09/01/2024",
    modelPageUrl: "https://deepmind.google/models/gemini/pro/",
    pricingUrl: "https://www.google.com/pricing",
    websiteUrl: "https://www.google.com/",    
  },
  {
    id: "23",
    provider: "Google",
    name: "google:gemini-2.0-flash",
    displayName: "Gemini 2.0 Flash",
    description: "Gemini 2.0 Flash delivers next-gen features and improved capabilities, including superior speed, native tool use, and a 1M token context window.",
    contextWindow: 1048576,
    maxOutputTokens: 8192,
    parameters: {
      temperature: 0.7,
      maxTokens: 8192,
      topP: 1,
    },
    pricing: {
      inputPrice: 0.10,
      outputPrice: 0.40,
    },
    inputTypes: {
      text: true,
      image: true,
      audio: true,
      video: true,
    },
    knowledgeCutoff: "08/01/2024",
    modelPageUrl: "https://deepmind.google/models/gemini/pro/",
    pricingUrl: "https://www.google.com/pricing",
    websiteUrl: "https://www.google.com/",    
  },
  {
    id: "24",
    provider: "Google",
    name: "google:gemini-2.0-flash-lite",
    displayName: "Gemini 2.0 Flash-Lite",
    description: "A Gemini 2.0 Flash model optimized for cost efficiency and low latency.",
    contextWindow: 1048576,
    maxOutputTokens: 8192,
    parameters: {
      temperature: 0.7,
      maxTokens: 8192,
      topP: 1,
    },
    pricing: {
      inputPrice: 0.075,
      outputPrice: 0.30,
    },
    inputTypes: {
      text: true,
      image: true,
      audio: true,
      video: true,
    },
    knowledgeCutoff: "08/01/2024",
    modelPageUrl: "https://deepmind.google/models/gemini/pro/",
    pricingUrl: "https://www.google.com/pricing",
    websiteUrl: "https://www.google.com/",    
  },
  {
    id: "25",
    provider: "Google",
    name: "google:gemini-2.0-flash-preview-image-generation",
    displayName: "Gemini 2.0 Flash Preview Image Generation",
    description: "Gemini 2.0 Flash Preview Image Generation delivers improved image generation features, including generating and editing images conversationally.",
    contextWindow: 32000,
    maxOutputTokens: 8192,
    parameters: {
      temperature: 0.7,
      maxTokens: 8192,
      topP: 1,
    },
    pricing: {
      inputPrice: 0,
      outputPrice: 0.03,
    },
    inputTypes: {
      text: true,
      image: true,
      audio: true,
      video: true,
    },
    knowledgeCutoff: "08/01/2024",
    modelPageUrl: "https://deepmind.google/models/gemini/pro/",
    pricingUrl: "https://www.google.com/pricing",
    websiteUrl: "https://www.google.com/",    
  },
  {
    id: "26",
    provider: "Google",
    name: "google:gemini-2.5-flash-preview-05-20",
    displayName: "Gemini 2.5 Flash Preview",
    description: "Our best model in terms of price-performance, offering well-rounded capabilities. Gemini 2.5 Flash rate limits are more restricted since it is an experimental / preview model.",
    contextWindow: 1048576,
    maxOutputTokens: 65536,
    parameters: {
      temperature: 0.7,
      maxTokens: 65536,
      topP: 1,
      thinking: {
        type: "enabled",
        budget_tokens: 10000,
      }
    },
    pricing: {
      inputPrice: 0.15,
      outputPrice: 0.60,
      audioInputPrice: 1.00,
      thinkingOutputPrice: 3.50,
    },
    inputTypes: {
      text: true,
      image: true,
      audio: true,
      video: true,
    },
    knowledgeCutoff: "01/01/2025",
    modelPageUrl: "https://deepmind.google/models/gemini/pro/",
    pricingUrl: "https://www.google.com/pricing",
    websiteUrl: "https://www.google.com/",    
  },
  {
    id: "27",
    provider: "Google",
    name: "google:gemini-2.5-pro-preview-05-06",
    displayName: "Gemini 2.5 Pro Preview",
    description: "Gemini 2.5 Pro is our state-of-the-art thinking model, capable of reasoning over complex problems in code, math, and STEM, as well as analyzing large datasets, codebases, and documents using long context. Gemini 2.5 Pro rate limits are more restricted since it is a preview model.",
    contextWindow: 1048576,
    maxOutputTokens: 65536,
    parameters: {
      temperature: 0.7,
      maxTokens: 65536,
      topP: 1,
      thinking: {
        type: "enabled",
        budget_tokens: 10000,
      }
    },
    pricing: {
      inputPrice: 2.50,
      outputPrice: 15.00,
    },
    inputTypes: {
      text: true,
      image: true,
      audio: true,
      video: true,
    },
    knowledgeCutoff: "01/01/2025",
    modelPageUrl: "https://deepmind.google/models/gemini/pro/",
    pricingUrl: "https://www.google.com/pricing",
    websiteUrl: "https://www.google.com/",    
  },
]

export const defaultSession: Session = {
  id: uuidv4(),
  name: 'New Session',
  modelId: 'openai:gpt-4o-mini',
  model: models[0],
  parameters: { temperature: 0.7, max_tokens: 2048, top_p: 1 },
  ragEnabled: false,
  contextDocs: [],
  messages: [],
  userInput: '',
  isSynced: false,
}